name: Lint code with Rubocop

on: [push, pull_request]

jobs:
  build:
    runs-on: #{{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
	bundler-cache: true

    - name: Run Rubocop
      run: bundle exec rubocop